name: Publish CloudResumeChallenge

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::042889969210:role/GitHubOIDC-LambdaDeploy
          aws-region: us-east-1

      - name: Publish CloudResumeChallenge.html to S3
        run: |
          aws s3 cp CloudResumeChallenge.html s3://subrealstudios.com/CloudResumeChallenge.html
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3QFBB3COE2N4Y \
            --paths "/CloudResumeChallenge.html"
