name: Deploy GeoTracker Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t ./package

    - name: Run unit tests
      run: |
        python -m pytest tests
        
    - name: Package Lambda function
      run: |
        cp GeoTracker.py ./package/
        cd package
        zip -r ../lambda.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code \
          --function-name GeoTracker \
          --zip-file fileb://lambda.zip
